package com.jsblock;

import com.jsblock.block.APGDoorDRL;
import com.jsblock.block.APGGlassDRL;
import com.jsblock.block.APGGlassEndDRL;
import com.jsblock.block.AuthorizeButton;
import com.jsblock.block.AutoDoor;
import com.jsblock.block.Bufferstop1;
import com.jsblock.block.ButterflyLight;
import com.jsblock.block.Ceiling1;
import com.jsblock.block.CircleWall;
import com.jsblock.block.DeparturePole;
import com.jsblock.block.DepartureTimer;
import com.jsblock.block.EmgStop1;
import com.jsblock.block.EmgStop5;
import com.jsblock.block.EmgStop6;
import com.jsblock.block.EnquiryMachine1;
import com.jsblock.block.EnquiryMachine2;
import com.jsblock.block.EnquiryMachine3;
import com.jsblock.block.EnquiryMachine4;
import com.jsblock.block.ExitSign1e;
import com.jsblock.block.ExitSign1o;
import com.jsblock.block.FareSaver1;
import com.jsblock.block.HelpLine1;
import com.jsblock.block.HelpLine2;
import com.jsblock.block.HelpLine3;
import com.jsblock.block.HelpLine4;
import com.jsblock.block.InterCarBarrier1Left;
import com.jsblock.block.InterCarBarrier1Middle;
import com.jsblock.block.InterCarBarrier1Right;
import com.jsblock.block.KCREmgStopSign;
import com.jsblock.block.KCRNameSign;
import com.jsblock.block.KCRNameSignStationColored;
import com.jsblock.block.Light1;
import com.jsblock.block.Light2;
import com.jsblock.block.LightBlock;
import com.jsblock.block.MTRStairs1;
import com.jsblock.block.ModelE44;
import com.jsblock.block.PIDS1A;
import com.jsblock.block.PIDSLCD;
import com.jsblock.block.PIDSRV;
import com.jsblock.block.PIDSRVSIL1;
import com.jsblock.block.PIDSRVSIL2;
import com.jsblock.block.RVPIDSPole;
import com.jsblock.block.SignalLightBlue;
import com.jsblock.block.SignalLightGreen;
import com.jsblock.block.SignalLightInverted1;
import com.jsblock.block.SignalLightInverted2;
import com.jsblock.block.SignalLightRed1;
import com.jsblock.block.SignalLightRed2;
import com.jsblock.block.SoundLooper;
import com.jsblock.block.StationCeiling1;
import com.jsblock.block.StationCeiling1StationColored;
import com.jsblock.block.StationCeilingPole;
import com.jsblock.block.StationNameStanding;
import com.jsblock.block.SubsidyMachine1;
import com.jsblock.block.TicketBarrier1;
import com.jsblock.block.TicketBarrier1Decor;
import com.jsblock.block.TrespassSign1;
import com.jsblock.block.TrespassSign2;
import com.jsblock.block.TrespassSign3;
import com.jsblock.block.WaterMachine1;
import mtr.RegistryObject;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.material.MapColor;

public interface Blocks {
    RegistryObject<Block> APG_DOOR_DRL = new RegistryObject<>(APGDoorDRL::new);
    RegistryObject<Block> APG_GLASS_DRL = new RegistryObject<>(APGGlassDRL::new);
    RegistryObject<Block> APG_GLASS_END_DRL = new RegistryObject<>(APGGlassEndDRL::new);
    RegistryObject<Block> AUTO_IRON_DOOR = new RegistryObject<>(() -> new AutoDoor(BlockBehaviour.Properties.copy(net.minecraft.world.level.block.Blocks.IRON_DOOR)));
    RegistryObject<Block> BUTTERFLY_LIGHT = new RegistryObject<>(() -> new ButterflyLight(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_BLACK).mapColor(MapColor.COLOR_BLACK).requiresCorrectToolForDrops().strength(3.0f).lightLevel(state -> 4)));
    RegistryObject<Block> BUFFERSTOP_1 = new RegistryObject<>(() -> new Bufferstop1(BlockBehaviour.Properties.of().requiresCorrectToolForDrops().strength(4.0f).lightLevel(state -> 15).noOcclusion()));
    RegistryObject<Block> CEILING_1 = new RegistryObject<>(() -> new Ceiling1(BlockBehaviour.Properties.of().requiresCorrectToolForDrops().strength(2.0f).noOcclusion()));
    RegistryObject<Block> CIRCLE_WALL_1 = new RegistryObject<>(CircleWall::new);
    RegistryObject<Block> CIRCLE_WALL_2 = new RegistryObject<>(CircleWall::new);
    RegistryObject<Block> CIRCLE_WALL_3 = new RegistryObject<>(CircleWall::new);
    RegistryObject<Block> CIRCLE_WALL_4 = new RegistryObject<>(CircleWall::new);
    RegistryObject<Block> CIRCLE_WALL_5 = new RegistryObject<>(CircleWall::new);
    RegistryObject<Block> CIRCLE_WALL_6 = new RegistryObject<>(CircleWall::new);
    RegistryObject<Block> CIRCLE_WALL_7 = new RegistryObject<>(CircleWall::new);
    RegistryObject<Block> DEPARTURE_POLE = new RegistryObject<>(() -> new DeparturePole(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_BLACK).requiresCorrectToolForDrops().strength(3.0f).noOcclusion()));
    RegistryObject<Block> DEPARTURE_TIMER = new RegistryObject<>(() -> new DepartureTimer(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_BLACK).requiresCorrectToolForDrops().strength(3.0f)));
    RegistryObject<Block> ENQUIRY_MACHINE_1 = new RegistryObject<>(() -> new EnquiryMachine1(BlockBehaviour.Properties.of().requiresCorrectToolForDrops().strength(4.0f)));
    RegistryObject<Block> ENQUIRY_MACHINE_2 = new RegistryObject<>(() -> new EnquiryMachine2(BlockBehaviour.Properties.of().requiresCorrectToolForDrops().strength(4.0f)));
    RegistryObject<Block> ENQUIRY_MACHINE_3 = new RegistryObject<>(() -> new EnquiryMachine3(BlockBehaviour.Properties.of().requiresCorrectToolForDrops().strength(4.0f).lightLevel(state -> 4).emissiveRendering((state, world, pos) -> true)));
    RegistryObject<Block> ENQUIRY_MACHINE_4 = new RegistryObject<>(() -> new EnquiryMachine4(BlockBehaviour.Properties.of().requiresCorrectToolForDrops().strength(4.0f).lightLevel(state -> 4).emissiveRendering((state, world, pos) -> true)));
    RegistryObject<Block> EMG_STOP_1 = new RegistryObject<>(() -> new EmgStop1(BlockBehaviour.Properties.of().requiresCorrectToolForDrops().strength(1.0f)));
    RegistryObject<Block> EMG_STOP_5 = new RegistryObject<>(() -> new EmgStop5(BlockBehaviour.Properties.of().requiresCorrectToolForDrops().strength(4.0f).lightLevel(state -> 15).noOcclusion()));
    RegistryObject<Block> EMG_STOP_6 = new RegistryObject<>(() -> new EmgStop6(BlockBehaviour.Properties.of().requiresCorrectToolForDrops().strength(4.0f).lightLevel(state -> 8).emissiveRendering((state, world, pos) -> true).noOcclusion()));
    RegistryObject<Block> EXIT_SIGN_1O = new RegistryObject<>(() -> new ExitSign1o(BlockBehaviour.Properties.of().requiresCorrectToolForDrops().strength(1.5f).lightLevel(state -> 5).emissiveRendering((state, world, pos) -> true)));
    RegistryObject<Block> EXIT_SIGN_1E = new RegistryObject<>(() -> new ExitSign1e(BlockBehaviour.Properties.of().requiresCorrectToolForDrops().strength(1.5f).lightLevel(state -> 5).emissiveRendering((state, world, pos) -> true)));
    RegistryObject<Block> FARESAVER_1 = new RegistryObject<>(() -> new FareSaver1(BlockBehaviour.Properties.of().requiresCorrectToolForDrops().strength(4.0f).lightLevel(state -> 15)));
    RegistryObject<Block> HELPLINE_1 = new RegistryObject<>(() -> new HelpLine1(BlockBehaviour.Properties.of().requiresCorrectToolForDrops().strength(1.0f)));
    RegistryObject<Block> HELPLINE_2 = new RegistryObject<>(() -> new HelpLine2(BlockBehaviour.Properties.of().requiresCorrectToolForDrops().strength(1.0f)));
    RegistryObject<Block> HELPLINE_3 = new RegistryObject<>(() -> new HelpLine3(BlockBehaviour.Properties.of().requiresCorrectToolForDrops().strength(4.0f).noOcclusion()));
    RegistryObject<Block> HELPLINE_4 = new RegistryObject<>(() -> new HelpLine4(BlockBehaviour.Properties.of().requiresCorrectToolForDrops().strength(4.0f).lightLevel(state -> 15).noOcclusion()));
    RegistryObject<Block> INTER_CAR_BARRIER_1_LEFT = new RegistryObject<>(() -> new InterCarBarrier1Left(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_YELLOW).requiresCorrectToolForDrops().strength(1.0f)));
    RegistryObject<Block> INTER_CAR_BARRIER_1_MIDDLE = new RegistryObject<>(() -> new InterCarBarrier1Middle(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_YELLOW).requiresCorrectToolForDrops().strength(1.0f)));
    RegistryObject<Block> INTER_CAR_BARRIER_1_RIGHT = new RegistryObject<>(() -> new InterCarBarrier1Right(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_YELLOW).requiresCorrectToolForDrops().strength(1.0f)));
    RegistryObject<Block> KCR_NAME_SIGN = new RegistryObject<>(() -> new KCRNameSign(BlockBehaviour.Properties.of().requiresCorrectToolForDrops().strength(5.0f).lightLevel(state -> 10).emissiveRendering((state, world, pos) -> true)));
    RegistryObject<Block> KCR_NAME_SIGN_STATION_COLOR = new RegistryObject<>(() -> new KCRNameSignStationColored(BlockBehaviour.Properties.of().requiresCorrectToolForDrops().strength(5.0f).lightLevel(state -> 10).emissiveRendering((state, world, pos) -> true)));
    RegistryObject<Block> KCR_EMG_STOP_SIGN = new RegistryObject<>(() -> new KCREmgStopSign(BlockBehaviour.Properties.of().requiresCorrectToolForDrops().strength(3.0f).noOcclusion()));
    RegistryObject<Block> LIGHT_1 = new RegistryObject<>(() -> new Light1(BlockBehaviour.Properties.of().requiresCorrectToolForDrops().strength(2.0f).lightLevel(state -> 15)));
    RegistryObject<Block> LIGHT_2 = new RegistryObject<>(() -> new Light2(BlockBehaviour.Properties.of().requiresCorrectToolForDrops().strength(2.0f).lightLevel(state -> 15).noOcclusion()));
    RegistryObject<Block> LIGHT_BLOCK = new RegistryObject<>(() -> new LightBlock(BlockBehaviour.Properties.of().air().requiresCorrectToolForDrops().strength(1.0f).lightLevel(state -> state.getValue(LightBlock.LIGHT_LEVEL)).noOcclusion()));
    RegistryObject<Block> OP_BUTTONS = new RegistryObject<>(() -> new AuthorizeButton(BlockBehaviour.Properties.of().requiresCorrectToolForDrops().strength(1.0f).lightLevel(state -> 8).noOcclusion()));
    RegistryObject<Block> MODEL_E44 = new RegistryObject<>(() -> new ModelE44(BlockBehaviour.Properties.of().requiresCorrectToolForDrops().strength(0.5f).noOcclusion()));
    RegistryObject<Block> MTR_STAIRS_1 = new RegistryObject<>(() -> new MTRStairs1(BlockBehaviour.Properties.of().requiresCorrectToolForDrops().strength(0.5f).noOcclusion()));
    RegistryObject<Block> PIDS_1A = new RegistryObject<>(PIDS1A::new);
    RegistryObject<Block> PIDS_LCD = new RegistryObject<>(PIDSLCD::new);
    RegistryObject<Block> PIDS_RV_TCL = new RegistryObject<>(PIDSRV::new);
    RegistryObject<Block> PIDS_RV_SIL_1 = new RegistryObject<>(PIDSRVSIL1::new);
    RegistryObject<Block> PIDS_RV_SIL_2 = new RegistryObject<>(PIDSRVSIL2::new);
    RegistryObject<Block> RV_PIDS_POLE = new RegistryObject<>(() -> new RVPIDSPole(BlockBehaviour.Properties.of().requiresCorrectToolForDrops().strength(1.0f).noOcclusion()));
    RegistryObject<Block> SIGNAL_LIGHT_RED_1 = new RegistryObject<>(() -> new SignalLightRed1(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_BLACK).requiresCorrectToolForDrops().strength(1.0f)));
    RegistryObject<Block> SIGNAL_LIGHT_RED_2 = new RegistryObject<>(() -> new SignalLightRed2(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_BLACK).requiresCorrectToolForDrops().strength(1.0f)));
    RegistryObject<Block> SIGNAL_LIGHT_BLUE = new RegistryObject<>(() -> new SignalLightBlue(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_BLACK).requiresCorrectToolForDrops().strength(1.0f)));
    RegistryObject<Block> SIGNAL_LIGHT_GREEN = new RegistryObject<>(() -> new SignalLightGreen(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_BLACK).requiresCorrectToolForDrops().strength(1.0f)));
    RegistryObject<Block> SIGNAL_LIGHT_INVERTED_1 = new RegistryObject<>(() -> new SignalLightInverted1(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_BLACK).requiresCorrectToolForDrops().strength(1.0f)));
    RegistryObject<Block> SIGNAL_LIGHT_INVERTED_2 = new RegistryObject<>(() -> new SignalLightInverted2(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_BLACK).requiresCorrectToolForDrops().strength(1.0f)));
    RegistryObject<Block> SOUND_LOOPER = new RegistryObject<>(() -> new SoundLooper(BlockBehaviour.Properties.copy(net.minecraft.world.level.block.Blocks.SMOOTH_STONE)));
    RegistryObject<Block> STATION_CEILING_1 = new RegistryObject<>(() -> new StationCeiling1(BlockBehaviour.Properties.of().requiresCorrectToolForDrops().strength(4.0f).noOcclusion()));
    RegistryObject<Block> STATION_CEILING_1_STATION_COLOR = new RegistryObject<>(() -> new StationCeiling1StationColored(BlockBehaviour.Properties.of().requiresCorrectToolForDrops().strength(4.0f).noOcclusion()));
    RegistryObject<Block> STATION_CEILING_POLE = new RegistryObject<>(() -> new StationCeilingPole(BlockBehaviour.Properties.of().requiresCorrectToolForDrops().strength(1.0f).noOcclusion()));
    RegistryObject<Block> STATION_NAME_TALL_STAND = new RegistryObject<>(StationNameStanding::new);
    RegistryObject<Block> SUBSIDY_MACHINE_1 = new RegistryObject<>(() -> new SubsidyMachine1(BlockBehaviour.Properties.of().requiresCorrectToolForDrops().strength(4.0f)));
    RegistryObject<Block> TICKET_BARRIER_1_ENTRANCE = new RegistryObject<>(() -> new TicketBarrier1(true));
    RegistryObject<Block> TICKET_BARRIER_1_EXIT = new RegistryObject<>(() -> new TicketBarrier1(false));
    RegistryObject<Block> TICKET_BARRIER_1_DECOR = new RegistryObject<>(TicketBarrier1Decor::new);
    RegistryObject<Block> TRESPASS_SIGN_1 = new RegistryObject<>(() -> new TrespassSign1(BlockBehaviour.Properties.of().requiresCorrectToolForDrops().strength(2.0f).noOcclusion()));
    RegistryObject<Block> TRESPASS_SIGN_2 = new RegistryObject<>(() -> new TrespassSign2(BlockBehaviour.Properties.of().requiresCorrectToolForDrops().strength(1.0f).noOcclusion()));
    RegistryObject<Block> TRESPASS_SIGN_3 = new RegistryObject<>(() -> new TrespassSign3(BlockBehaviour.Properties.of().requiresCorrectToolForDrops().strength(2.0f).noOcclusion()));
    RegistryObject<Block> WATER_MACHINE_1 = new RegistryObject<>(() -> new WaterMachine1(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_BLACK).requiresCorrectToolForDrops().strength(4.0f)));
}